---
# This playbook installs the OSKAR website on Centos 7
# This is a flask app deployed using gunicorn with nginx as a proxy server
# Systemd is used to manage both nginx and the gunicorn wsgi flask app


# TODO: Create a user to host the website in? eg oskar-web

- hosts: all
  become_method: sudo
  # Override default role variables
  vars:
    server_domain_or_ip: 192.168.199.100
    ansible_users_group: vagrant  # Group of the user which the website is run from.
  # Run the following roles
  roles:
    - common
    - project
