# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.hostname = 'oskar-web'
  config.vm.network :private_network, ip: "192.168.199.100"

  config.vm.provider :virtualbox do |vb|
    vb.name = 'oskar-web'
    vb.memory = "2048"
    vb.cpus = 1
  end
end
