---
# file: project/tasks/main.yml

- name: Checkout project code
  git:
    repo: https://github.com/bmort/oskar_web_test
    dest: oskar_web.git
    update: yes
    version: HEAD


- name: Update pip
  pip:
    name: pip
    state: latest
  become: True


- name: Install virtualenv
  pip:
    name: virtualenv
    state: latest
  become: True

- name: Install requirements (using virtualenv in the oskar_web.git folder)
  pip:
    requirements: /home/vagrant/oskar_web.git/oskar_web/requirements.txt
    virtualenv: /home/vagrant/oskar_web.git/venv

- name: Run gunicorn
  gunicorn:
    app: wsgi
    chdir: /home/vagrant/oskar_web.git/oskar_web
    conf: /home/vagrant/oskar_web.git/oskar_web/gunicorn.cfg.py
    venv: /home/vagrant/oskar_web.git/venv
